name: Start MongoDB Server

on: [push, pull_request]

jobs:
  mongodb-action:
    name: Start MongoDB Server v${{ matrix.mongodb-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4']
        mongodb-db: ['ci']
        mongodb-username: ['ci']
        mongodb-password: ['ci']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: ${{ matrix.mongodb-db }}
          mongodb-username: ${{ matrix.mongodb-username }}
          mongodb-password: ${{ matrix.mongodb-password }}
